[home]
phoenix ansible_host=127.0.0.1 ansible_connection=local
sterling ansible_host=192.168.0.136 ansible_user=[USER] ansible_connection=ssh ansible_shell_type=cmd

[bms]
gemini ansible_host=10.0.1.201 ansible_user=[USER]
nuk1 ansible_host=10.0.1.252 ansible_user=[USER]
lab1 ansible_host=10.0.1.75 ansible_user=[USER]
lab2 ansible_host=10.0.1.139 ansible_user=[USER]
lab3 ansible_host=10.0.1.30 ansible_user=[USER]
lab4 ansible_host=10.0.1.238 ansible_user=[USER]

[ollama_herd:children]
home
bms
